"""empty message

Revision ID: 7dff8e898631
Revises: a353562a7424
Create Date: 2021-07-29 08:31:38.215101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dff8e898631'
down_revision = 'a353562a7424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###
