"""empty message

Revision ID: fc5040ef8c4c
Revises: 7dff8e898631
Create Date: 2021-07-30 03:02:13.127576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5040ef8c4c'
down_revision = '7dff8e898631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'website_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'website_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
